image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cahe/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install tox
    - tox

run:
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist/*.tar.gz

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH